redis:
  host: 127.0.0.1
  db: 15
database:
  host: localhost
  port: 3306
  username: root
  password: root
  database: nest-admin
  # 自动删除实体
  dropSchema: false
  # 自动同步实体到数据库
  synchronize: true
logger:
  # 日志级别
  level: debug
