redis:
  host: 127.0.0.1
  db: 15
database:
  host: localhost
  port: 3306
  username: root
  password: root
  database: nest-admin
  dropSchema: false
  synchronize: false
logger:
  # 日志级别
  level: debug
  lokiHost: http://localhost:3100
  transports:
    # 控制台输出
    - console
    # 文件输出
    - file
    # 采集到loki
    - loki
