app:
  name: nest快速开发平台
  description: 一个node的快速开发平台,使用nestjs、typeorm、mysql、redis、swagger、jwt等技术栈开发
  version: 0.1.0
  prefix: /
  port: 7001
  platformHeader: platform
jwt:
  # token 密钥
  secret: DFmCuCzt6GEMtdd0tfgPhtdyUElG1TTW
  # access token 过期时间
  accessExpiresIn: 1D
  # refresh token 过期时间
  refreshExpiresIn: 7D
# 本地文件上传配置
localFile:
  # 本地文件存储路径
  basePath: /file
  # 最大文件大小(M)
  maxFileSize: 20
